import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { Poppins } from 'next/font/google';


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">

      <body className={`antialiased ${poppins.variable} font-sans`}>
        <div className="min-h-screen bg-background-default text-text-primary">
          <ThemeRegistry>{children}</ThemeRegistry>
        </div>
      </body>

    </html>
  );
}
